apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 
      https://github.com/dzidzi91/devops-home-lab.git
    targetRevision: HEAD
    path: k8s/devops-platform
  destination:
    server: https://kubernetes.default.svc
    namespace: devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
