apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-platform
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-platform
  template:
    metadata:
      labels:
        app: devops-platform
    spec:
      containers:
        - name: devops-platform
          image: 192.168.56.10:5000/devops-platform-app:build-127
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: APP_NAME
              value: "devops-platform"
            - name: APP_ENV
              value: "k8s"
            - name: APP_VERSION
              value: "build-127"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: devops-platform
  namespace: devops
spec:
  selector:
    app: devops-platform
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080